version: '3.9'

services:
  mysql:
    image: "mysql:8.0.32"
    container_name: glpi_db
    volumes:
      - emh_glpi_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: glpi_db
    ports:
      - "33061:3306"
    networks:
      - emh_glpi
networks:
  emh_glpi:
    driver: bridge

volumes:
  emh_glpi_db:
    driver: local
